-- THIS LINE IS USED TO CREATE DATABASE
-- CREATE DATABASE DB_NAME
CREATE DATABASE university;



-- THIS LINE IS USED WHEN WE ARE USING DATABASE
-- USE DB_NAME
USE university;


-- THIS LINE IS USED TO CREATE TABLE
-- CREATE TABLE TABLE_NAME

CREATE TABLE collegestudent(
	rollnum INT PRIMARY KEY,
    name VARCHAR(50),
    age INT NOT NULL
);

-- 1 WAY OF INSERTING DATA INTO TABLE--  

INSERT INTO collegestudent VALUES ( 1,"SUMIT",21);
INSERT INTO collegestudent VALUES (2,"BHADWAJ",22);
INSERT INTO collegestudent values (3,"JAY",23);



-- 2 WAY OF INSERTING DATA INTO TABLE--  
INSERT INTO collegestudent(rollnum,name,age) 
VALUES
(4,"KUMAR",24),
(5,"AKSHAY",55),
(6,"SIDDARTH",39),
(7,"RANBIR",40);


-- FOR DELETING DATABASE FROM SYSTEM
-- DROP DATABASE DB_NAME
DROP DATABASE college;


-- FOR SEEING ALL THE DATABSES IN THE SYSTEM
SHOW DATABASES; 

CREATE DATABASE college;


DROP DATABASE IF EXISTS college;

-- IF EXISTS GIVES WARNING IF THE DATABSE DOES NOT EXIST
DROP DATABASE IF EXISTS student;



